Replacing Table join by User id, song id
krishrustagi/emotunes-backend pull request #20
Opened 2023-04-02 16:59 UTC by krishrustagi

2023-04-03 03:51 UTC, SarthakSavasil requested changes

2023-04-03 03:51 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/dao/UserSongMappingDao.java
>      public List<SongMetadata> getAll(String userId) {
function Name...

2023-04-03 03:51 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/dao/UserSongMappingDao.java
>          List<SongMetadata> songMetadataList = new ArrayList<>();
break the function into 2 from here and return the function call directly

2023-04-03 03:51 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/dao/UserSongMappingDao.java
> +        userSongMappingList.forEach(userSongMapping -> {
Repeated Code.. Use function

2023-04-03 03:51 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/dao/UserSongMappingDao.java
> +        userSongMappingList.forEach(userSongMapping -> {
Again

2023-04-03 03:51 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/dao/UserSongMappingDao.java
> +        String songId = songRepository.getIdByTitleAndDuration(songMetadata.getTitle(),
Ispe krte discuss... I dont think ki id pass krne mai koi issue hona chaiye... Google bhikiya tha as such koi negative article nhi mila

2023-04-03 03:51 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/repository/SongRepository.java
> +    String getIdByTitleAndDuration(String title, LocalTime duration);
fetching with duration is not a good idea.. krte discuss id wale ke saath

2023-04-04 03:40 UTC, SarthakSavasil requested changes

2023-04-04 03:40 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/controller/SongPlayerController.java
> +    public void play(@RequestParam("song_url") String songUrl) {
Do we need it? ye frontend pe hi handle hoga na

2023-04-04 03:40 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/controller/SongPlayerController.java
>      public ResponseEntity<String> songNotPerEmotion(
Function name should be more specific. This function is suggesting a different emotion for a song right? toh thoda wesa naam de de

2023-04-04 03:40 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/service/impl/SongPlayerServiceImpl.java
>      public ResponseEntity<String> songNotPerEmotion(
Return string only not response entity

2023-04-04 03:40 UTC, SarthakSavasil commented on src/main/java/com/emotunes/emotunes/service/impl/SongPlayerServiceImpl.java
> -            String userId, SongMetadata songMetadata, boolean isLiked) {
here too

2023-04-04 08:49 UTC, krishrustagi commented on src/main/java/com/emotunes/emotunes/controller/SongPlayerController.java
>      public ResponseEntity<String> songNotPerEmotion(
Let's not move away from the motive of this PR. Putting a todo comment.

2023-04-04 08:49 UTC, krishrustagi commented on src/main/java/com/emotunes/emotunes/service/impl/SongPlayerServiceImpl.java
>      public ResponseEntity<String> songNotPerEmotion(
let's change later

2023-04-04 08:49 UTC, krishrustagi commented on src/main/java/com/emotunes/emotunes/service/impl/SongPlayerServiceImpl.java
> -            String userId, SongMetadata songMetadata, boolean isLiked) {
changed in another PR

2023-04-04 10:33 UTC, SarthakSavasil approved these changes

2023-04-04 10:35 UTC, merged