Predict song emotion - Part 1
krishrustagi/emotunes-backend pull request #30
Opened 2023-04-05 17:15 UTC by krishrustagi

2023-04-05 18:16 UTC, SarthakSavasil requested changes

2023-04-05 18:16 UTC, SarthakSavasil commented on emotunes-commons/src/main/java/com/emotunes/emotunes/dao/SongsDao.java
> +    public List<StoredSong> getAll() {
getAllSongs, findAllSongs krde

2023-04-05 18:16 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/AdminServiceImpl.java
> +            Emotion songEmotion = null;
205 to 211 ek function bana sakta

2023-04-05 18:16 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/AdminServiceImpl.java
> +            Emotion songEmotion = null;
yaha bhi hai same cheez cuz

2023-04-05 18:16 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/UserSongModelServiceImpl.java
> +        BufferedReader in = new BufferedReader(new InputStreamReader(process.getInputStream()));
bufferedReader should also be closed using finally block

2023-04-05 18:16 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/UserSongModelServiceImpl.java
> +        Process process = processBuilder.start();
process builder aur process mai bhi dekh lena close ya destroy ya aisa kuch hota ho to

2023-04-05 18:50 UTC, krishrustagi commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/UserSongModelServiceImpl.java
> +        Process process = processBuilder.start();
done

2023-04-06 03:27 UTC, SarthakSavasil approved these changes

2023-04-06 16:13 UTC, merged