Re train cron setup
krishrustagi/emotunes-backend pull request #64
Opened 2023-05-02 16:24 UTC by krishrustagi

2023-05-02 18:18 UTC, SarthakSavasil requested changes

2023-05-02 18:18 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/AdminServiceImpl.java
> +        map.put("song_url", songUrl);
Kaam kr gya?

2023-05-02 18:18 UTC, SarthakSavasil commented on emotunes-feign/src/main/java/com/emotunes/emotunes/client/MachineLearningClient.java
> +    @PostMapping(value = "v1/re_train")
underscore use mt kr hiphen kr

2023-05-02 18:18 UTC, SarthakSavasil commented on emotunes-commons/src/main/java/com/emotunes/emotunes/repository/UserSongEmotionPreferenceRepository.java
> +    List<List<String>> findUserIdSongIdWithUserCountLimit(long limit);
list of tuple use krna chaiye wese, but agr work kr rha hai to chhod

2023-05-02 18:18 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/SchedulingServiceImpl.java
> +            songUrlListOfUser.add(songUrl);
ye loop ke bahr hona chaiye, song ids ki list pass kr upar list of tuple nikal aur map mai convert kr as songid, urls

2023-05-05 13:54 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/SchedulingServiceImpl.java
> +        List<String> songUrlList = songsDao.getSongUrls(songIdList);
song url direct fetch krke alag se map kiya hai iski jagah ek tuple fetch krte with (song_id, song_url) waha se map mai daalte.
Like abhi agr main query manipulate krta hoon ya pagination daalta hoon ya order by to ye logic galat map kr dega

Agr time lagega to ese hi rehne de

2023-05-05 13:54 UTC, SarthakSavasil commented on emotunes-admin/src/main/java/com/emotunes/emotunes/service/impl/SchedulingServiceImpl.java
> +        List<String> modelWeightsUrlList = userDao.getModelWeightsUrls(userIdList);
same

2023-05-05 13:54 UTC, SarthakSavasil commented on emotunes-commons/src/main/java/com/emotunes/emotunes/constants/AzureStorageConstans.java
> +    public static final String MODEL_WEIGHTS_CONTAINER = "thumbnails";
iski value thumbnail hi hogi?

2023-05-05 13:54 UTC, SarthakSavasil commented on emotunes-commons/src/main/java/com/emotunes/emotunes/repository/SongRepository.java
> +    List<String> getSongUrls(List<String> songIdList);
is  jagah bol rha List<Tuple> tuple->songid, songUrl

2023-05-05 13:55 UTC, SarthakSavasil approved these changes

2023-05-05 15:07 UTC, krishrustagi commented on emotunes-commons/src/main/java/com/emotunes/emotunes/repository/SongRepository.java
> +    List<String> getSongUrls(List<String> songIdList);
done

2023-05-05 18:56 UTC, merged